/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 to enable debug mode */
#define DEBUG_MODE 1

/* Define to 1 to fox-config has been used for configuration */
#define HAS_FOX_CONFIG 

/* Define to 1 if glXGetProcAddress is present */
#define HAS_OGL_GETPROC 1

/* Define to 1 if glXGetProcAddressARB is present */
#define HAS_OGL_GETPROC_ARB 1

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Define to 1 if you have the <fox-1.2/fx.h> header file. */
/* #undef HAVE_FOX_1_2_FX_H */

/* Define to 1 if you have the <fox-1.3/fx.h> header file. */
/* #undef HAVE_FOX_1_3_FX_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you compile for a Unix OS. */
/* #define OS_UNIX 1 */

/* Define to 1 if you compile for a Windows OS. */
#define OS_W32 1

/* Name of package */
#define PACKAGE "denormgen"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "roland@rptd.dnsalias.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "DRPG Sprite Viewer"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "DRPG Spriter Viewer 1.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "drpgsprview"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.0"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */
